import { create } from "zustand";

export const useStore = create((set) => ({
	// user data
	user: null,
	setUser: (user) => set((prev) => ({ user })),

	// collection data
	collection: [
			{
				adult: false,
				backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
				genre_ids: [28, 53, 80],
				id: 603692,
				original_language: "en",
				original_title: "John Wick: Chapter 4",
				overview:
					"With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
				popularity: 3911.607,
				poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
				release_date: "2023-03-22",
				title: "John Wick: Chapter 4",
				video: false,
				vote_average: 7.942,
				vote_count: 2836,
			},
			{
				adult: false,
				backdrop_path: "/7dzngS8pLkGJpyeskCFcjPO9qLF.jpg",
				genre_ids: [28, 53],
				id: 245891,
				original_language: "en",
				original_title: "John Wick",
				overview:
					"Ex-hitman John Wick comes out of retirement to track down the gangsters that took everything from him.",
				popularity: 85.237,
				poster_path: "/wXqWR7dHncNRbxoEGybEy7QTe9h.jpg",
				release_date: "2014-10-22",
				title: "John Wick",
				video: false,
				vote_average: 7.411,
				vote_count: 17483,
			},
			{
				adult: false,
				backdrop_path: null,
				genre_ids: [28, 12, 80, 53],
				id: 730629,
				original_language: "en",
				original_title: "John Wick: Chapter 5",
				overview:
					"The fifth installment in the John Wick franchise, confirmed to be in development.",
				popularity: 24.923,
				poster_path: null,
				release_date: "",
				title: "John Wick: Chapter 5",
				video: false,
				vote_average: 0,
				vote_count: 0,
			},
			{
				adult: false,
				backdrop_path: null,
				genre_ids: [],
				id: 619022,
				original_language: "en",
				original_title: "John Wick: Assassin's Code (Extra)",
				overview: "John Wick Movie Extra",
				popularity: 46.774,
				poster_path: "/fJbw16AwM59dEhSiCIAfFGgIgOP.jpg",
				release_date: "2015-02-03",
				title: "John Wick: Assassin's Code (Extra)",
				video: true,
				vote_average: 8.014,
				vote_count: 36,
			},
			{
				adult: false,
				backdrop_path: "/r17jFHAemzcWPPtoO0UxjIX0xas.jpg",
				genre_ids: [28, 53, 80],
				id: 324552,
				original_language: "en",
				original_title: "John Wick: Chapter 2",
				overview:
					"John Wick is forced out of retirement by a former associate looking to seize control of a shadowy international assassins’ guild. Bound by a blood oath to aid him, Wick travels to Rome and does battle against some of the world’s most dangerous killers.",
				popularity: 145.849,
				poster_path: "/hXWBc0ioZP3cN4zCu6SN3YHXZVO.jpg",
				release_date: "2017-02-08",
				title: "John Wick: Chapter 2",
				video: false,
				vote_average: 7.319,
				vote_count: 11634,
			},
			{
				adult: false,
				backdrop_path: "/vVpEOvdxVBP2aV166j5Xlvb5Cdc.jpg",
				genre_ids: [28, 53, 80],
				id: 458156,
				original_language: "en",
				original_title: "John Wick: Chapter 3 - Parabellum",
				overview:
					"Super-assassin John Wick returns with a $14 million price tag on his head and an army of bounty-hunting killers on his trail. After killing a member of the shadowy international assassin’s guild, the High Table, John Wick is excommunicado, but the world’s most ruthless hit men and women await his every turn.",
				popularity: 146.877,
				poster_path: "/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg",
				release_date: "2019-05-15",
				title: "John Wick: Chapter 3 - Parabellum",
				video: false,
				vote_average: 7.447,
				vote_count: 9335,
			},
			{
				adult: false,
				backdrop_path: null,
				genre_ids: [99],
				id: 600991,
				original_language: "en",
				original_title: "Training 'John Wick'",
				overview:
					"A look at the fight choreography being developed for the film.",
				popularity: 14.594,
				poster_path: "/1x1fEoDe3GKBYh4iR4jhrouRXzT.jpg",
				release_date: "2017-06-13",
				title: "Training 'John Wick'",
				video: true,
				vote_average: 6.957,
				vote_count: 23,
			},
			{
				adult: false,
				backdrop_path: "/vWNGnjBB3pa6R8slwjhwDxRqBUf.jpg",
				genre_ids: [99],
				id: 651445,
				original_language: "en",
				original_title: "John Wick Chapter 2: Wick-vizzed",
				overview:
					"A candid look at rehearsal footage in support of a focus on pre-viz.",
				popularity: 20.585,
				poster_path: "/qQFBj2tBlkKhAcAgDVpdFWLX5x.jpg",
				release_date: "2017-06-13",
				title: "John Wick Chapter 2: Wick-vizzed",
				video: true,
				vote_average: 7.392,
				vote_count: 60,
			},
			{
				adult: false,
				backdrop_path: null,
				genre_ids: [99],
				id: 600987,
				original_language: "en",
				original_title: "Don't F*#% With John Wick",
				overview:
					"Behind the scenes look at fight choreography and action training.",
				popularity: 6.576,
				poster_path: "/d3m7SxiehljQ2r5dIHg7fGjfLXp.jpg",
				release_date: "2015-02-03",
				title: "Don't F*#% With John Wick",
				video: false,
				vote_average: 7.558,
				vote_count: 26,
			},
			{
				adult: false,
				backdrop_path: null,
				genre_ids: [99],
				id: 600990,
				original_language: "en",
				original_title: "John Wick: Calling in the Cavalry",
				overview:
					"Short documentary that looks at a number of elements like the initial pitch for the project and the 2nd Unit action sequences.",
				popularity: 4.991,
				poster_path: "/gps49Xqjv0C6Kplb9jgDVAaE9CF.jpg",
				release_date: "2015-02-03",
				title: "John Wick: Calling in the Cavalry",
				video: false,
				vote_average: 7.029,
				vote_count: 17,
			},
			{
				adult: false,
				backdrop_path: null,
				genre_ids: [99],
				id: 1036194,
				original_language: "en",
				original_title:
					"As Above, So Below: The Underworld of 'John Wick'",
				overview:
					"A close look at the assassin's lifestyle in the film.",
				popularity: 3.854,
				poster_path: null,
				release_date: "2017-06-13",
				title: "As Above, So Below: The Underworld of 'John Wick'",
				video: true,
				vote_average: 7.4,
				vote_count: 5,
			},
		],
	addItem: (item) => set((prev) => ({ collection: [item, ...collection] })),
}));
